### ISSUE TITLE
`Optimization Moro.ipynb` has multiple issues that prevent it from running

### ISSUE THREAD

**Issue by EwoutH** [quaquel/epa1361_open#7]
The [Optimization Moro.ipynb](https://github.com/quaquel/epa1361_open/blob/91d2b63942c576aaf617bddedd55286fb3c72a04/final%20assignment/Optimization%20Moro.ipynb) notebook crashes in multiple different places, preventing the notebook to run all the way though. So far we've encountered the following errors:

1. The first `MultiprocessingEvaluator` will fail because `uncertainty_sampling` expects a Sampler, and not the string `'mc'`. 
2. The same `MultiprocessingEvaluator` will fail after that **for a second time**  with an NumPy error, `numpy.ndarray' object has no attribute 'uncertainties'`, because a Tuple is inputted instead of a Model.
Change cell 5 to `model, _ = get_model_for_problem_formulation(1)` to save only the Model in `model` and not the whole tuple.
3. Then cell 11 will crash because pandas and seaborn aren't imported.
4. ~And only then you will come on the case in Cell 21 (ln 60 in the Git version), in which the `evaluator.robust_optimize()` keeps running endlessly.~
**Edit:** It runs, but just quite slow, and in that time it doesn't update the progress bar, or the expected time.
5. Cell 24 gives a `KeyError: 'policy'`, because the `experiments` DataFrame doesn't contain a `'policy'` column.

We also tried running it with the EMAworkbench [2.0.9](https://pypi.org/project/ema-workbench/2.0.9/), which was released at the time of last year's course. Only the first error (with the Sampler) in the list above is prevented, but all other still had to be fixed.

~There might be more errors after the fourth error, but I couldn't get past it. It doesn't give any error codes, just keeps running endlessly, both with the `MultiprocessingEvaluator` and `SequentialEvaluator`. It might be related to #5, or maybe not.~ It just runs very long without updating the progress bar. A firth error is experienced afterwards.

@quaquel could you check if you can run the whole notebook and upload the fixed version?

---

On a bit of a broader note, I really don't mind a bit of debugging, but at this point we poured dozens of person-hours into this debugging the code and notebooks, and aren't able to spend this time into modelling in support of decision making. We feel the directed search is an integral part of this process and we love to focus on that instead of debugging. I think this course can provide far more value and learning experience to students if debugging the examples and source code is a (way) smaller part of the course.

**Comment by EwoutH** [comment]
@quaquel I also noticed you removed the whole _1.3 Re-evaluate candidate solutions under uncertainty_ section. Can you give a bit of explanation why?

**Comment by quaquel** [comment]
The short answer is to safe time. The longer answer is that this is identical to any of the MORDM style assignments from week 5-6.
