### ISSUE TITLE
Upstream dike_model performance improvement

### ISSUE THREAD

**Issue by EwoutH** [quaquel/epa1361_open#8]
I just made a few model changes which made the model about 2x faster (everything tested and validated). Is the `dike_model` still being used somewhere in production or academics? In that case I can share the code in advance.

If this model is used in next year's course I will open a PR and the end of the quarter, it will save students lots of time.

**Comment by EwoutH** [comment]
I will open a PR after the June 17th deadline.

**Comment by EwoutH** [comment]
I found some time to properly evaluate the performance (turns out it's even 3.9 times faster) and write up the validation neatly. I opened a PR here: https://github.com/quaquel/epa1361_open/pull/13.

**Comment by quaquel** [comment]
Thanks for this. That makes quite a difference indeed.
